export const symptoms1 = ["Fever", "Ulcers", "Facial Swelling", "Swelling on leg", "Short term lethargy", "Swollen lymph nodes", "Diarrhea with muscus", "Strong cough", "Inflammed eye", "Lesions in the nasal cavity", "Hair loss", "Greenish-yellow nasal discharge", "Jaundice", "Poor coat apperence", "Watering", "Straining", "Upset stomach", "Allergic Reaction", "Limping", "Eye ulcer", "Pnemonia", "Seizures", "Bloody Urine", "Loss of eat", "Dark or black face", "Appetite varies", "Sickness", "Nasal Bleeding", "Gasc", "Shaking head", "Attacks", "Blood stool", "Nasal discharge", "Polyuria", "Exessive Urination", "Convulsion", "Wheezing", "Weekness", "Lession on cat skin", "Lethargy", "Skin irritation", "Floopy muscle", "Sensitivity to bright light", "Tenderness", "Scaly patches of skin", "Fatty stool", "Nausea", "Most often none", "Discomfort", "Loss of appetite", "Rhinitis", "Immediate death", "Pox lession on skin", "Red on affected area", "Chills", "Watering Diarrhea", "loss in weight", "emaciation", "egg production decreases", "weakened legs", "abortion at the end of gestation", "swollen", "Distress", "Animal become lame", "Difficulty in breathing", "Fluif Faeces on blood and muscle", "Pneumoniaآ", "Slightly Swollen", "Dull", "Severe", "Depression", "Normal appetite", "Swelling", "Inability to stand", "Excitability", "Attack", "Ulcer on gum", "Animal gets uneasy", "Body stiffness", "Sickness", "Sudden death", "Abortion", "Small red bumps", "Ataxia", "Ring shaped Lesion", "Bubbles in the mouth", "Changes in outer layer skin", "Red Tinge", "Passing of undigested food", "Smell", "Loss of activity", "Bald patches", "Poor condition", "Heavy infection", "Muscle weakness", "Thicked skin", "General malaise", "Oedema", "Poor growth", "Dullness", "Vomiting", "Partial Paralysis", "Thick Crusting", "Constant pacing", "Loss od appetite", "Indigestion", "Blood in urine", "Malaise", "Lack of coordination", "Sores on lip", "Abortion on late pregancy", "paresis", "Hemolytic anemia", "Abortion", "Runny nose", "Dark colored bloody", "Dysentery", "Decreased milk", "Swelling of udder", "Wound lesion", "Emaciation", "SkinAllergy", "Berberi", "Gastritis", "Severe headache", "Tiredness", "Decreased appetite", "Gas", "Drooping ears", "Edema", "Drooping wings", "Weakness", "Neck paralysis", "Dejection", "Severe swellimg", "Hepatitis", "Sneezing", "Shallow breathing", "Dyspnea", "Rhinorrhea", "Mortality", "Air sacculitis", "Labored breathing", "Hemopytsis", "Restlessness", "Stripped remiges", "Apathy", "Lepatomegaly", "Balance problem", "Legness", "Sour Throat", "Difficulty in feeding", "Forthy eye", "Inappentence", "Lack of walking", "Scabs On feet", "Enlarged Thymus", "Fluffed Feather", "Difficultty in Breathing", "Heavy Breathing", "Puffed_up Feather", "Swollen Abdomen", "Tail Wagging", "Overweight", "Skin infection", "Discharge From eyes", "Retarded Growth", "Pale comb", "Vision Problem", "Liquid Dropping", "Undigested in their feces", "Sharp Feather", "Ruffled Appearance", "Sinuses", "Feather Loss", "Watery Eyes", "Bony Lesion", "Tremor of head and neck", "Swollen Belly", "Succumb", "Signs in rams", "Spines", "Discharge", "Hemoglobinuria", "Sweats", "Excess salivation", "Incoordination", "Wasting", "Muscle twiching", "Teeth griding", "Head tilt", "Decreased growth of bone", "Swollen left abdomen", "Cessation of eructation", "Excession Salivation", "Barren ewes", "Tremor", "Tachypea", "lllthrift", "Bloody droping", "haemorrhage", "Bloody Diarhhea", "Reluctant Move", "Poor wool", "Poor immune function", "Abdominal pain", "Fetopelvic dispropotion", "Watery Diarrhea dispropotion", "Severe kerititis", "Testical Pain", "Foul Smelling", "Sheep often bites", "Rub", "Jaundice", "Reduce Reproductive potential", "Pyrexia", "Red skin", "Groosly enlarged", "Hyperexcitability", "Decreased eyelid", "Muscus", "Pot belly", "Bottle jaw", "Strange behaviour", "Clearly unthrifty", "Infected navels", "Foot Hot", "Unsteady Gait", "Smell of ammonia", "Wandering", "Cell Damage", "Formation of vesicles", "Skeleten abnormalities", "Wether restless", "Listless", "Thivk skin", "Dizzines", "Tear production", "Anversion to light", "Bluish white opacity", "Skin color change", "Radip onset", "Head Shking", "Discomfort", "Isolation from flock", "Listless", "Head tossing", "Coughingآ", "cough", "sneeze", "Shortness of breath.", "Gasping", "Excessive blood loss", "Nosebleedآ", "Bleeding from other parts of the body", "Bad breath", "extending its neck", "difficulty swallowing", "weakness", "Eye redness", "Excessive eye watering", "Sudden death", "unable to urinate", "Extreme thirst", "Egg production stops", "Broody behavior", "Continuous loss of weight", "Regurgitation of food", "loss of appetite", "lathargy", "head tilt", "respiratory noise", "muscular stiffness", "sweating", "muscular spasms", "thirst", "high body temperaure", "dry or tacky gums", "reduced appetite", "lying down", "outstretched neck", "inappetence", "noisy breathing", "self-isolation", "recumbency", "muscles problem", "changed gait", "diffuse", "difficulty diagnosis", "swelling problem", "bleeding from wounds", "frequent yawning", "undernutrition", "drinking polluted water", "listlessness", "stumbling", "drooling", "feline infections", "lymphosarcoma", "stomatitis", "anaemia", "high temperature", "rapid pulse and heart rates", "lameness in affected leg", "swollen teats", "eye discharges", "change their normal behaviour", "stop eating", "stop drinking", "Diffulty Swallowing", "Excessive drooling", "Staggering"]

export const symptoms2 = ["Diarrhea", "Difficulty breathing", "Loss of appetite", "Anoxeria", "Respiratory distress", "Poor Appetite", "Bloody Drool", "Thrist and urination", "Painfull", "Loss of appetite", "Difficulty walking", "Abdominal pain", "Reduce Energy", "Chronic eye inflamation", "Swelling of face or leg", "Tensemus", "Runny nose", "Coughing", "Eye and Skin change", "Lesions on nose", "Dandruff", "Lack of pigmentation", "Pneumoniaآ", "No appp", "Anaemia", "Willnot run to jump", "Congestion", "Eye disharge", "Hydrophobia", "Diffculty breathing", "Fell unwell", "Lesions", "Scabs", "Lumps", "Blood in stool", "Stomach growling", "Scartching ear", "Black on ear", "Periodic vommiting", "Anemia", "Nosebleeds", "inflamed nostrils", "Change in gait", "Loss of consciousness", "Rapid Breathing", "Weekness", "Dandruff in cat coat", "Red patches", "Scartching", "Speech delay", "Intellectual disability", "Disharge from affected eye", "Inflammation", "Clouded cornea", "Erythema", "Salivation", "Decrease appetite", "Sore", "Distended stomach", "Eyeproblem", "Liver disease", "Nuerological", "Mild sneezing", "Nasal", "Ocular discharge", "Dry or dull hair", "Grinding teeth", "Enteritis", "Pox lession on skin", "Skin reashes", "Horny growth", "Wart-like growth", "Skin ulcer", "Exhaustion", "ruffled feathers", "swollen purple wattle", "Swollen comb", "thirst", "Closed eyes", "los of the ability to walk", "Mammary glads", "Fatigue", "weak calves", "Join pains", "red-colored", "hot udder", "Trembling", "Staggering", "Slightly Swollen", "Lession on the skin", "Milky Hard", "Hind quarted soil", "Animal stop feed", "Blood on faces", "Appetite", "Relunctance to move", "Swelling may occur under jaw", "Heat", "Hardness", "Redness", "Bottle Jaw", "Nervousness", "hyper sensitivity", "Painfull Swalling", "Dribbling of saliva", "Inability of Swalllon Feeding", "Moist and painfull", "Blooody Fluid", "Red Diarrhea", "Faeces are streake with blood", "Stand with head droping", "Abnormal behaviour", "Papules appear on teats anad udder", "Decrease in milk production", "Milk reduce", "Drop in milk production", "Pot belly", "Dry Hair coat", "Bite other animals", "Eye become dull", "Red eye", "Yellowish Discharge", "Consistency of milk", "Difficult in respiration", "Excessive production", "Stamping And pedding of hind eye", "Severe colic", "Obscure Lameness", "Round patches", "Dry skin", "Size of lesions vary", "Stumbling", "loss of appetite", "Progressive weakness", "Joint Pain", "Vitamin and minerals defiency", "Headache", "Nausea", "Hair tining", "Scabbing", "Itchiness", "Loss of earing", "Head ache", "Throat and Ear pain", "Hepatic failure", "Nause", "Muscle Loss", "Skeleten pain", "Wasting", "Short stature", "Enlargement of bones", "Sweat", "Fatique", "Lacrimation", "Seizures", "Uncharacteristic hiding", "Stopped eat", "Poor coat condition", "Infection of the skin", "Stiffness", "Trembling", "White mark on the muscle", "Loss of vitamin E", "Staggering as drunk", "Self Mutilation", "Acting aggressive", "Acting unnaturally tame", "Skin rashes", "Watery eye", "Facial muscle twitching", "abnormalalities", "Seizuers", "Fatique", "Abdminal pain", "Constipation", "Malaise", "Stomach cramps", "Infection", "Sores on lower leg and teats", "Mummification", "Stillbirth", "Weak kids", "Incoordination", "Terminal convulsion", "Mucous discharge", "Reduce feed", "Weight gain", "Holding limbs off the ground", "Wool production", "change in milk", "Swollen", "Tender to touch", "Occular discharge", "Mouth lesion", "Excess salivary", "Difficult in walking", "Edema in lower jaw", "Shivering", "Reduce growth", "Kid moratality", "Dullness", "Wound", "Dizziness", "Redness of white of the eye", "Swelling of eyelid", "Cornea become cloudy", "Wasting", "Nervous", "morbidity", "Bloody", "Mortality", "Severe headache", "Swollen kidney", "Hematuria", "Decreased appetite", "Abdominal discomfort", "Lack of coordination", "Listlessness", "Decresed egg production", "Greenish diarrhea", "Yellow or green dropping", "Purplish combs", "Wattles", "Drop on egg production", "ruffled feathers", "Labored breathing", "Lacrimation", "Anorexia", "Paralyzed leg", "Slow growth", "Lesion", "High moratality", "Epistaxis", "Unilateral Nasal discharge", "Gagging", "Retching", "Halitosis", "Death", "Facial edema", "Dyspnea", "Conjuctivtis", "Pharyngitis", "Congestion", "Neurologic sign", "Asymptomatic", "Blue straws", "Less Feather growth", "Defienciency in vitamin", "Dilation of duodenum", "Cloacal pasting", "Congestion", "Splenomegaly", "Swollen", "Shaking oh head", "Abdominal destention", "Neck Paralysis", "Paresis", "Shortness of breath", "mortality", "Preening", "Beak overgrowth", "Ear infection", "Torticollis", "Tremors of the head", "Roughened", "Small and yellow bumps", "Dry Scabs", "Redness", "Trachea", "Thickening of skin", "Obstructed Lungs", "Snoring", "Yellow Eye", "Diphtherictic", "Tail_Bobbing", "Sleeping Excessively", "Headache", "Half-closed eye", "Stress", "Secondary Infection", "Chest Pain", "Lame", "Difficulty in Swallowing", "Ataxia", "Loss of pigment", "Clubbed Feather", "Eye disharge", "Loss of powder down", "Green Dropping", "Swollen Eyelids", "Misshapen Beak", "Itching", "Nervous Issue", "Anorexia", "Kicking at the belly", "Exercise in tolerance", "Dullness", "Spread of infection", "Signs in ewe", "Underdeveloped muscles", "Semen Examination", "Reduce Lamp marking", "Unusally thin", "Enlarged skulls", "Sudden Abortion", "loss of appetite", "Muscle aches", "Blood Poisioning", "Dehydration", "Deability", "Lameness", "Apathy", "Ruminal stasis", "Watery faeces", "Weak Pulse", "Colic", "Hyperaestesia", "Hock joint", "Circling", "Muscles ache", "Blindness", "Grunting", "Lying Down", "Extension of neck", "Abnormal conformation", "Ulcerated muscle", "Ulcerated ear", "Poor conformation", "Hairy Fleeces", "Swelling of head and neck", "Skin Lesion", "Flank", "Rump", "Small intestines", "Flock Moratality", "Straw colored", "Carcass decomposes", "Small size", "Poor Body condition", "Achomotrica", "Malpresentation", "Shock", "Sick", "Corneal Ulceration", "Conjunctive", "Iris prolapse", "Loss of eye", "Itches", "Bloody discharge", "Dirty", "Stained Wool", "Tail shaking", "Fleece become thin", "Loss of wool", "Rough Hair coat", "Agalactia", "Loss of milk production", "Sloughing of the tail", "Oral lesion", "Moist", "Flabby", "Raw", "Sensitive to touch", "Skin may thicken", "Muscular Spasms", "Gums", "Very cold skin", "Lip", "Colic", "Blood Clots", "Strange behaviour", "Good appetite", "Relunctance to walk", "Painfull to touch", "Warm", "Stamping And pedding of hind eye", "Jerky limb movements", "Pruritis", "Difficulty in rising", "Hot joints", "Pustulses", "Difficulty in Walk", "Nostrils", "Abnormally long leg", "Scabs on lip", "Facial defects", "Flat ribs", "Underdeveloped muscles", "Kicking", "Normal appetite", "Attempt to urinate", "Stiffness", "Sluggish", "Oxygen defiency", "Fast breathing", "Bleeding wounds", "Skin issue", "panting", "facial swelling", "Production of mucus", "droopy wings", "twisted neck", "chirping", "mild weakness", "dizziness and fainting", "Blurry vision", "watery eyes", "slow growth", "Trauma", "Nose picking", "Dry air", "confusion", "loss of alertness", "Pawing at the face or nose", "gasping for air", "gasping for breath", "difficulty swallowing", "decreased stool production", "distended stomach", "heavy breathing", "restless movement", "Frequent eye Infections", "Crusty eye lashes and matting of eyelashes", "foul smelling stools", "آ increased passing gas", "Mucus discharge from the eye", "آ rapid heartbeats", "fluffed feathers", "lack of vocalizations", "Lightheadednessآ", "droopiness", "rectal bleeding", "inability to fly", "loss ofآ wariness", "Broody behavior", "Constipation", "experiencing changes in weight", "آ pain and bloating", "burning ache or pain", "wheezing", "Excessive food intake", "Undigested seeds", "abortion", "gurgling sound", "loss of tail tone", "respiratory noise", "nasal discharge", "swollen lymph nodes", "difficulty moving and eating", "lack of appetite", "dry or tacky gums", "listlessness", "frequent yawning", "rapid pulse and heart rates", "depression", "teats", "tiredness", "behaviour", "high body temperature", "Diffulty Swallowing", "Excessive drooling", "Staggering"];

export const symptoms3 = ["Vomiting", "Seizuers", "Poor Appetite", "Foul Breath", "Nasal Discharge", "Weekness in the back legs", "Back Pain", "Stiffness", "Lameness", "Poor Appetite", "Depression", "Watery Stool", "Flatulence", "Sneezing", "Lethargy", "Loss of appettite", "Limping", "Unable to exercise", "Joint Pain", "Noisy Breathing", "Crusting of the skin", "Pain on face", "Weight loss", "pain", "Dehydration", "Blindness", "Muscle pain", "Muscle stiffness", "Distended chest", "Pain on leg", "Pink eye", "Arthritis", "Jaw is dropped", "Swelling", "Lameness", "Fell unwell", "Skin issue", "Raised growth or bump", "Diffulty chewing", "Bumps(black,grey or red)", "Bad smell", "Coughing", "Weight loss", "Polydipsa", "Inability to jump", "chewing", "Twitching", "Salivating", "Swallowing", "Effort to breath", "Hair loss", "Excessive grooming", "Walking problem", "Eye movements", "Rubbing eye", "Cramps", "Scartch", "Hair loss", "Pain", "Firm", "Swelling in the bite area", "Liver disease", "Nasal", "Dyspnea", "Blood from mouth", "Shock", "Blindness", "abscessess", "Torticollis", "Septicemia", "Stomach cramps", "Blue colored lip", "Bloody discharge", "Mortality varies", "Red skin", "Lesions on ear", "Ruffled Coat", "diarrhoea", "Inability to absorb nutrients", "Distinctive bumps", "Facial swelling", "Fluif filled blisters", "Swelling of internal organs", "Milk getting out more watery", "Milk getting out more thick", "Convulsion", "Prostrat", "Moist and painfull", "Sudden Death", "Abnormal behaviour", "Decrease in milk production", "Weakness", "Hyper sensitivity", "Painfull", "Red eye", "Bloody Diarrhea", "Colic", "Weakness", "Ataxia", "Respiratory infection", "Slim over the shell", "Easily damage shell", "Flaking of the Scutes", "Gas or bloating", "Excess sleeping", "Folded Ears", "Rough coat", "Eventually death", "Crusty", "Flaky", "Red lesion from bald patches", "Enlarged lymph nodes", "Abdonormal discomfort", "Nausea", "Scabbing", "Itchiness", "Vomiting", "Head ache", "Throat and Ear pain", "Abdonormal pain", "Nause", "Wasting", "Weigth bearing long bones", "Fatique", "Vomitting", "Lacrimation", "Anorexia", "Dehydration", "Stopped eat", "Fatique", "Loss of vitamin E", "Acting aggressive", "Acting unnaturally tame", "Pain", "abnormalalities", "Fatique", "Nausea", "Facial paralysis", "Lesion", "Weakness", "Stomach cramps", "pulmonary congestion", "Jaundice", "Weak kids", "Weakness", "Pox lesion", "Incoordination", "Immediate death", "Reduce feed", "Tender to touch", "Shivering", "Weakness", "Dullness", "Head ache", "Dizziness", "Tear production", "Wasting", "Nervous", "Bloody", "Mortality", "Vomiting", "Bloody", "Nausea", "Wasting", "Listlessness", "Greenish diarrhea", "Lesion", "Pain", "Gagging", "Retching", "Weight loss", "Halitosis", "Death", "Facial edema", "Dyspnea", "Conjuctivtis", "Pharyngitis", "Congestion", "Neurologic abnormalities", "Sudden death", "Urine retention", "Depression", "Anorexia", "Lethargy", "Weight loss", "Asymptomatic", "Epistaxis", "Death", "Less Feather growth", "Defienciency in vitamin", "Dilation of duodenum", "Cloacal pasting", "Swollen", "Shaking oh head", "Neck Paralysis", "Paresis", "Shortness of breath", "mortality", "Blindness", "Distinctive bumps", "Preening", "Beak overgrowth", "Ear infection", "Torticollis", "Weakness", "Swelling", "Emaciation", "Tremors of the head", "Dehydration", "Roughened", "Small and yellow bumps", "Dry Scabs", "Redness", "Trachea", "Thickening of skin", "Obstructed Lungs", "Snoring", "Yellow Eye", "Diphtherictic", "Tail_Bobbing", "Sleeping Excessively", "Headache", "Half-closed eye", "Seizures", "Stress", "Secondary Infection", "Coughing", "Sneezing", "Fatique", "Chest Pain", "Lame", "Death", "Swolling of joint", "Eye closed", "Difficulty in Swallowing", "Weakness", "Vision Problem", "Emaciation", "Difficulty in breathing", "Ataxia", "Seizures", "Loss of pigment", "Undigested in their feces", "Clubbed Feather", "Eye disharge", "Loss of powder down", "Green Dropping", "Swollen Eyelids", "Misshapen Beak", "Itching", "Nasal Discharge", "Nervous Issue", "Anorexia", "Weakness", "Kicking at the belly", "Exercise in tolerance", "Dullness", "Depressio"]

export const symptoms4 = ["Weight loss",
"Tiredness",
"Vomiting",
"Lethargy",
"Hyperesthesia",
"Tarry Stool",
"Unable To Eat",
"Broken Bones",
"Rapid Heart Rate",
"Stiffness",
"Lameness",
"Depression",
"Flatulence",
"Eye and Skin change",
"Noisy Breathing",
"Crusting of the skin",
"pain ",
"Muscle pain",
"Week legs",
"Jaw is dropped",
"Blood in faces",
"Lumps",
"Stomach growling",
"Bad smell",
"Sneezing",
"Twitching",
"Swallowing",
"Hair loss",
"Discharge from eye",
"Walking problem",
"Clouded cornea",
"Cramps",
"Scartch",
"Salivation",
"Firm",
"Limp",
"Liver disease",
"Nasal",
"Dyspnea",
"Blood from mouth",
"Grinding teeth",
"Blindness",
"Torticollis",
"Bloody discharge",
"Nasal discharge",
"Red skin",
"Exhaustion",
"Ruffled Coat",
"Weakness",
"Swollen comb",
"Distinctive bumps",
"Closed eyes",
"Mammary glads",
"Join pains",
"Milk getting out more watery",
"Staggering",
"Painfull Swalling",
"Inability of Swalllon Feeding",
"Red Diarrhea",
"Milky Hard",
"Animal stop feed",
"Appetite",
"Redness",
"Pot belly",
"Hyper sensitivity",
"Bite other animals",
"Painfull",
"Yellowish Discharge",
"Consistency of milk",
"Excessive production",
"Severe inflammation",
"Nausea",
"Inflammation of eye",
"Skin infection",
"Size of lesions vary",
"Colic",
"Stumbling",
"Easily damage shell",
"Gas or bloating",
"Excess sleeping",
"Dehydration",
"Flaky",
"Progressive weakness",
"Scabbing",
"Head ache",
"Diarrhea",
"White mark on the muscle",
"Acting aggressive",
"Skin rashes",
"Watery eye",
"Stomach cramps",
"Lesion",
"Endomeritis",
"pulmonary congestion",
"Weak kids",
"Pox lesion",
"Difficulty in breathing",
"Immediate death",
"Reduce feed",
"Tender to touch",
"Mouth lesion",
"Difficult in walking",
"Shivering",
"Cornea become cloudy",
"Mortality",
"Coughing",
"Hematuria",
"Wasting",
"Decresed egg production",
"Wattles",
"Labored breathing",
"Anorexia",
"Retching",
"Facial edema",
"Enteritis",
"Urine retention",
"Death",
"Defienciency in vitamin",
"Cloacal pasting",
"Swollen",
"Muscle aches",
"Beak overgrowth",
"Swelling",
"Dry Scabs",
"Thickening of skin",
"Half-closed eye",
"Chest Pain",
"Swolling of joint",
"Loss of powder down",
"Green Dropping",
"Itching",
"Exercise in tolerance",
"Urination",
"Semen Examination",
"Enlarged skulls",
"Death of lamb",
"congestion",
"Abortion",
"Deability",
"Ruminal stasis",
"Weak Pulse",
"Hock joint",
"Ulcerated muscle",
"Hairy Fleeces",
"Swelling on theBody",
"Pain",
"Rump",
"Abdominal discomfort",
"Loss of appetite",
"Small size",
"Shock",
"Iris prolapse",
"Scratches",
"Stained Wool",
"Nible at their wool",
"Loss of milk production",
"Raw",
"Edematous",
"Lip",
"Reduce milk ",
"Aneamia",
"Infected navels",
"Circling",
"Restlessness",
"Swelling on joints",
"Inappentence",
"Head Pressing",
"Tears",
"Jerky limb movements",
"Pruritis",
"Difficulty in Walk",
"Scabs on lip",
"Flat ribs",
"Attempt to urinate",
"Heat",
"Irritation",
"Odor to Ear",
"Scartches",
"Profuse",
"Hoarseness",
"Urine infection",
"Pawing at bedding",
"Bleeding wounds",
"Production of mucus",
"twisted neck",
"droopy wings",
"watery eyes",
"Nose picking",
"loss of alertness",
"difficulty swallowing",
"gasping for air",
"gasping for breath",
"heavy breathing",
"foul smelling stools",
"Mucus discharge from the eye",
"fluffed feathers",
"rectal bleeding",
"inability to fly",
"experiencing changes in weight",
"Excessive food intake",
"gurgling sound",
"urine dribbling",
"swollen lymph nodes",
"lying down",
"self-isolation",
"difficulty diagnosis",
"frequent yawning",
"drooling",
"stomatitis",
"lameness in affected leg",
"high body temperature",
]
export const symptoms5 = ["Dehydration",
"Pains",
"Anorexia",
"Sneezing",
"Blue Eye",
"Sudden death",
"Enlarged lymph nodes",
"Lossened Teeth",
"Enlarged lymph nodes or Swelling",
"Nasal Discharge",
"Week pulse",
"Vaginal Discharge",
"Severe weekness and depression",
"Swelling of joints",
"Neurologic abnormalities",
"Loss of appettite",
"Limping",
"Unable to exercise",
"Joint Pain",
"Lesions on nose",
"Ulcerated skin",
"Pain on face",
"Vomitting",
"Blindness",
"Muscle stiffness",
"Anaemia",
"Distended chest",
"Pain",
"Pain on leg",
"Pink eye",
"Arthritis",
"Shyness or aggression",
"Pale gums",
"Skin issue",
"Raised growth or bump",
"Bumps(black,grey or red)",
"Black stool",
"Red and inflammation ear",
"Periodic vommiting",
"Anemia",
"Lound breathing",
"Polydipsa",
"Inability to jump",
"Salivating",
"Effort to breath",
"Excessive grooming",
"Eye movements",
"Rubbing eye",
"Decrease appetite",
"Hair loss",
"Distended stomach",
"Nuerological",
"Ocular discharge",
"Shock",
"Lethargy",
"Septicemia",
"Stomach  cramps",
"Mortality varies",
"Lesions on ear",
"Swollen and painfull",
"diarrhoea",
"Lameness",
"Inability to absorb nutrients",
"Facial swelling",
"Diarrhea",
"Fluif filled blisters",
"Swelling of internal organs",
"Milk getting out more thick",
"Convulsion",
"Moist and painfull",
"Faeces are streake with blood",
"Abnormal behaviour",
"Papules appear on teats anad udd",
"Decrease in milk production",
"Milk reduce",
"Drop in milk production",
"Dry Hair coat",
"Weakness",
"Eye become dull",
"Bloody Diarrhea",
"Stamping And pedding of hind eye",
"Eye redness",
"Obscure Lameness",
"Ataxia",
"Respiratory infection",
"Flaking of the Scutes",
"Folded Ears",
"Eventually death",
"Red lesion from bald patches",
"Abdonormal discomfort",
"Itchiness",
"Throat and Ear pain",
"Abdonormal pain",
"Wasting",
"Weigth bearing long bones",
"Fatique",
"Seizures",
"Stopped eat",
"Loss of vitamin E",
"Acting unnaturally tame",
"Muscle pain",
"Nausea",
"Bleeding in eye and skin",
"Facial paralysis",
"Jaundice",
"Terminal convulsion",
"Weight gain",
"Wool production",
"Dullness",
"Dizziness",
"Tear production",
"Muscle aches",
"Bloody",
"Listlessness",
"Greenish diarrhea",
"Drop on egg production",
"Lesion",
"Weight loss",
"Infection",
"Dyspnea",
"Weightloss",
"Pharyngitis",
"Epistaxis",
"Congestion",
"Shaking oh head",
"Shortness of breath",
"Abnormalities",
"Emaciation",
"Snoring",
"Diphtherictic",
"Sleeping Excessively",
"Difficulty in Breathing",
"Chest Pain",
"Eye closed",
"Vision Problem",
"Bloody in feather",
"Misshapen Beak",
"Nervous Issue",
"Lying down",
"Reduce Lamp marking",
"Blood Poisioning ",
"Watery faeces",
"Colic",
"Extension of neck",
"Ulcerated ear",
"Flock Moratality",
"Carcass decomposes",
"Poor Body condition",
"Death",
"Loss of eye",
"Tenderness",
"Tail shaking",
"Scratching",
"Sloughing of the tail",
"Sensitive to touch",
"Fever",
"Blood Clots",
"Staggering",
"Good appetite",
"Depression",
"Increased in breathing",
"Recumbency",
"Not eating",
"Underdeveloped muscles",
"Stiffness",
"Oxygen defiency",
"Blister",
"Redness on ear",
"Neck Vein Swelling",
"Fatigue",
"droopy wings",
"swollen abdomen",
"twisted neck",
"slow growth",
"Dry air",
" dizziness and fainting",
"Bleeding from the nose",
"gasping for breath",
"extending its neck",
"restless movement",
"Frequent eye Infections",
"lack of vocalizations",
"Constipation",
"Undigested seeds",
"inability to rise",
"difficulty moving and eating",
"dull ness",
"coughing",
"drooping ears",
"urination problem",
"trembling",
]
